name = "vibefix-broken-ai-app-diagnosis"
main = "worker.js"
compatibility_date = "2026-06-03"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "VIBEFIX_KV"
id = "c31f2ba7390a4b17a7b58ea4b549abd5"

[vars]
FREE_AI_LIMIT = "3"
RAZORPAY_PAYMENT_LINK = "https://rzp.io/rzp/IJurCsfY"
UPGRADE_URL = "/payment.html"
